#!/usr/bin/env node
/**
 * audit:report — run all verify scripts and aggregate results.
 *
 * Output:
 *   - Console summary (human-readable)
 *   - .audit/report-YYYY-MM-DD.json (machine-readable, for trend tracking)
 *   - .audit/report-YYYY-MM-DD.md   (paste into PR description)
 *
 * Run via: pnpm audit:report
 */
import { execSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const REPORT_DIR = join(ROOT, ".audit");
const STAMP = new Date().toISOString().slice(0, 10);
const SHORT_SHA = (() => {
  try {
    return execSync("git rev-parse --short HEAD", { encoding: "utf8" }).trim();
  } catch {
    return "unknown";
  }
})();

mkdirSync(REPORT_DIR, { recursive: true });

const SCRIPTS = [
  { name: "go build", cmd: "go build ./...", blocking: true, viaShell: true },
  { name: "go vet", cmd: "go vet ./...", blocking: true, viaShell: true },
  { name: "go test", cmd: "go test ./...", blocking: true, viaShell: true },
  { name: "docs:check", cmd: "pnpm docs:check", blocking: true },
  { name: "verify:risk", cmd: "pnpm verify:risk", blocking: false },
  { name: "verify:cross-repo", cmd: "pnpm verify:cross-repo", blocking: true },
  { name: "verify:audit", cmd: "pnpm verify:audit", blocking: true },
];

const results = [];
for (const s of SCRIPTS) {
  const t0 = Date.now();
  try {
    const out = execSync(s.cmd, { encoding: "utf8", stdio: "pipe" });
    results.push({
      name: s.name,
      status: "pass",
      blocking: s.blocking,
      duration_ms: Date.now() - t0,
      stdout: out,
      stderr: "",
    });
  } catch (e) {
    const stdout = (e.stdout || "").toString();
    const stderr = (e.stderr || "").toString();
    const combined = stdout + stderr;
    const errors = (combined.match(/✖/g) || []).length +
                   (combined.match(/FAIL/g) || []).length;
    const warnings = (combined.match(/⚠/g) || []).length;
    results.push({
      name: s.name,
      status: e.status === 0 ? "pass" : "fail",
      blocking: s.blocking,
      duration_ms: Date.now() - t0,
      stdout,
      stderr,
      error_count: errors,
      warning_count: warnings,
    });
  }
}

const totalErrors = results.reduce((sum, r) => sum + (r.error_count || 0), 0);
const totalWarnings = results.reduce((sum, r) => sum + (r.warning_count || 0), 0);
const failed = results.filter((r) => r.status === "fail" && r.blocking);
const verdict =
  failed.length > 0 ? "🔴 FAIL" : totalErrors > 0 ? "🟠 ERRORS" : totalWarnings > 0 ? "🟡 WARN" : "🟢 PASS";

// --- JSON report ---
const jsonPath = join(REPORT_DIR, `report-${STAMP}.json`);
const jsonReport = {
  date: STAMP,
  commit: SHORT_SHA,
  verdict,
  scripts: results,
  totals: {
    errors: totalErrors,
    warnings: totalWarnings,
    failed_blocking: failed.length,
  },
};
writeFileSync(jsonPath, JSON.stringify(jsonReport, null, 2));

// --- Markdown report ---
const mdPath = join(REPORT_DIR, `report-${STAMP}.md`);
const mdLines = [];
mdLines.push(`# Audit Report — ${STAMP}`);
mdLines.push("");
mdLines.push(`- **Repo commit:** \`${SHORT_SHA}\``);
mdLines.push(`- **Verdict:** ${verdict}`);
mdLines.push(`- **Total errors:** ${totalErrors}`);
mdLines.push(`- **Total warnings:** ${totalWarnings}`);
mdLines.push("");
mdLines.push("## Script results");
mdLines.push("");
mdLines.push("| Script | Status | Duration | Errors | Warnings |");
mdLines.push("|---|---|---:|---:|---:|");
for (const r of results) {
  const icon = r.status === "pass" ? "✅" : r.blocking ? "❌" : "⚠";
  mdLines.push(
    `| \`${r.name}\` | ${icon} | ${r.duration_ms}ms | ${r.error_count || 0} | ${r.warning_count || 0} |`
  );
}
mdLines.push("");
if (failed.length > 0) {
  mdLines.push("## ❌ Failures (blocking)");
  mdLines.push("");
  for (const r of failed) {
    mdLines.push(`### \`${r.name}\``);
    mdLines.push("```");
    mdLines.push((r.stderr || r.stdout || "").trim());
    mdLines.push("```");
    mdLines.push("");
  }
}
mdLines.push("---");
mdLines.push("");
mdLines.push(`Generated by \`scripts/harness/audit-report.mjs\`. JSON: \`${jsonPath}\`.`);
writeFileSync(mdPath, mdLines.join("\n"));

// --- Console output ---
console.log("");
console.log(`Audit report — ${STAMP} @ ${SHORT_SHA}`);
console.log(`Verdict: ${verdict}`);
console.log("");
for (const r of results) {
  const icon = r.status === "pass" ? "✅" : r.blocking ? "❌" : "⚠";
  console.log(
    `  ${icon} ${r.name.padEnd(22)} ${String(r.duration_ms + "ms").padStart(8)}  ${r.error_count || 0} errors, ${r.warning_count || 0} warnings`
  );
}
console.log("");
console.log(`JSON: ${jsonPath}`);
console.log(`MD:   ${mdPath}`);

if (failed.length > 0) {
  process.exit(1);
}
